### ISSUE TITLE
I am Getting Cannot instantiate implementation type 'System.Net.Http.IHttpClientFactory' for service type 'System.Net.Http.IHttpClientFactory'. Error,

### ISSUE THREAD

**Issue by muzammil001** [CodeBeamOrg/CodeBeam.GoogleApis.Blazor#25]
blazor.webassembly.js:1 System.AggregateException: One or more errors occurred. (Cannot instantiate implementation type 'System.Net.Http.IHttpClientFactory' for service type 'System.Net.Http.IHttpClientFactory'.)
 ---> System.ArgumentException: Cannot instantiate implementation type 'System.Net.Http.IHttpClientFactory' for service type 'System.Net.Http.IHttpClientFactory'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(ICollection`1 descriptors)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, Boolean validateScopes)
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder.<>c__DisplayClass5_0.<.ctor>b__0()
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder.Build()
   at Program.<Main>$(String[] args) in D:\Software Projects\Tutorials\GoogleApiBlazor\GoogleApiBlazor\Program.cs:line 13
   --- End of inner exception stack trace ---

**Comment by mckaragoz** [comment]
Did you look at readme? You need to add `builder.Services.AddCodeBeamGoogleApiServices();` in program.cs

**Comment by muzammil001** [comment]
I did. It doesn't work.

**Comment by muzammil001** [comment]
can you make a tutorial video of this? that how does this work?

**Comment by muzammil001** [comment]
[GoogleApiBlazor.zip](https://github.com/CodeBeamOrg/CodeBeam.GoogleApis.Blazor/files/12064159/GoogleApiBlazor.zip)

here's my code. please review it.

**Comment by mckaragoz** [comment]
> [GoogleApiBlazor.zip](https://github.com/CodeBeamOrg/CodeBeam.GoogleApis.Blazor/files/12064159/GoogleApiBlazor.zip)
> 
> here's my code. please review it.

Find a solution. Add `builder.Services.AddHttpClient();` into you program.cs

**Comment by muzammil001** [comment]
I've added this, but it showing me same error.

**Comment by mckaragoz** [comment]
> I've added this, but it showing me same error.

Your project works on my computer. Remove the injection in Imports.razor and add into pages individually.

**Comment by muzammil001** [comment]
It works thanks, but I got another error. 
![Screenshot 2023-07-17 004708](https://github.com/CodeBeamOrg/CodeBeam.GoogleApis.Blazor/assets/31925129/fd628df1-32fa-41f5-b723-79418ad4c4bd)
